/**
 * Bundle the operational scripts into self-contained JavaScript.
 *
 * The production image is a Next.js standalone build: it contains only the
 * modules the *web app* traces, not `src/`, not `tsx`, and not the
 * devDependencies. Copying the TypeScript scripts into it is therefore not
 * enough — they import from `../src/lib/...`, which is not there, and nothing
 * in the image can execute TypeScript. Without this step you cannot create the
 * first administrator on a fresh deployment.
 *
 * esbuild inlines everything each script needs into one file per command, so
 * the image runs them with plain `node dist/cli/<name>.js`.
 *
 *   node scripts/build-cli.mjs
 */

import { build } from 'esbuild';
import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';

/** Commands that must be runnable on the server. */
const COMMANDS = [
  'seed-admin',
  'import-file',
  'maintenance',
  'sync-tally',
  'ingest-folder',
  'verify-reference',
];

const OUT_DIR = 'dist/cli';

/**
 * Left external because it cannot be bundled: the generated client resolves a
 * native query-engine binary at runtime, and the image already carries both
 * (`node_modules/@prisma` and `node_modules/.prisma`).
 */
const EXTERNAL = ['@prisma/client', '.prisma/client', '.prisma/client/default'];

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const result = await build({
    entryPoints: COMMANDS.map((c) => `scripts/${c}.ts`),
    outdir: OUT_DIR,
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    external: EXTERNAL,
    // Scripts are read by whoever is debugging a failed deploy at 9pm; keep
    // them legible and keep the stack traces pointing at real lines.
    minify: false,
    sourcemap: false,
    logLevel: 'warning',
    banner: {
      js: '// Generated by scripts/build-cli.mjs — do not edit. Source: scripts/*.ts',
    },
  });

  if (result.errors.length > 0) {
    console.error('Bundle failed.');
    process.exit(1);
  }

  console.log(`Bundled ${COMMANDS.length} commands into ${OUT_DIR}/`);
  for (const c of COMMANDS) {
    console.log(`  node ${path.posix.join(OUT_DIR, `${c}.js`)}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
