import { prisma } from '../src/lib/db';
import { getKpis, getByDimension, getExpenseAnalysis, getTrend, getComparisonMatrix, getFilterOptions } from '../src/lib/mis/engine';
import { drill } from '../src/lib/mis/drill';
const f=(n:number|null)=>n===null?'—':n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
async function main(){
  const c=(await prisma.company.findFirst())!;
  console.log('=== KPIs (unfiltered) ===');
  const k=await getKpis(c.id,{}); console.log(' rev',f(k.revenue),'exp',f(k.expense),'profit',f(k.profit),'margin',((k.margin??0)*100).toFixed(2)+'%');
  console.log('\n=== Streams ===');
  for(const r of await getByDimension(c.id,{},'stream')) console.log('  ',r.label.padEnd(10),f(r.revenue).padStart(16),f(r.expense).padStart(16),f(r.profit).padStart(16),((r.margin??0)*100).toFixed(2)+'%');
  console.log('\n=== Top 6 branches by margin ===');
  const br=(await getByDimension(c.id,{},'branch')).filter(b=>b.revenue>0).sort((a,b)=>(b.margin??-9)-(a.margin??-9));
  for(const r of br.slice(0,6)) console.log('  ',r.label.padEnd(8),f(r.revenue).padStart(16),f(r.expense).padStart(16),f(r.profit).padStart(16),((r.margin??0)*100).toFixed(2)+'%');
  console.log('\n=== Group analysis, Oct25, correct % ===');
  const g=await getExpenseAnalysis(c.id,{months:["Oct'25"]},'group');
  for(const r of g.slice(0,4)) console.log('  ',r.label.padEnd(32),f(r.amount).padStart(16),((r.pctOfRevenue??0)*100).toFixed(2)+'%');
  console.log('\n=== Group analysis, Oct25, LEGACY Looker % (should match PDF) ===');
  const gl=await getExpenseAnalysis(c.id,{months:["Oct'25"],legacyPercentMode:true},'group');
  for(const r of gl.slice(0,3)) console.log('  ',r.label.padEnd(32),f(r.amount).padStart(16),((r.pctOfRevenue??0)*100).toFixed(2)+'%  (PDF: 39.83 / 22.43 / 17.67)');
  console.log('\n=== Expense heads, Oct25, legacy % ===');
  const el=await getExpenseAnalysis(c.id,{months:["Oct'25"],legacyPercentMode:true},'account');
  for(const r of el.slice(0,3)) console.log('  ',r.label.padEnd(32),f(r.amount).padStart(16),((r.pctOfRevenue??0)*100).toFixed(2)+'%  (PDF: 40.96 / 23.99 / 18.78)');
  console.log('\n=== Trend ===');
  for(const t of await getTrend(c.id,{})) console.log('  ',t.periodLabel,t.financialYear,t.quarter,f(t.revenue),f(t.expense),f(t.profit));
  console.log('\n=== Drill: branch CKP ===');
  const d=await drill(c.id,{},{branch:'CKP'});
  console.log('  header',d.header.title,f(d.header.revenue),f(d.header.expense),((d.header.margin??0)*100).toFixed(2)+'%');
  for(const n of d.nodes.slice(0,4)) console.log('   ',n.label.padEnd(32),f(n.amount).padStart(14),((n.share??0)*100).toFixed(1)+'%');
  const opts=await getFilterOptions(c.id);
  console.log('\n=== Filter options ===');
  console.log('  fy',opts.financialYears,'months',opts.months.map(m=>m.label),'quarters',opts.quarters);
  console.log('  centres',opts.centres,'| streams',opts.streams,'| branches',opts.branches.length,'| groups',opts.groups.length,'| statuses',opts.statuses);
  const m=await getComparisonMatrix(c.id,{});
  console.log('  comparison matrix: branches',m.branches.length,'groups',m.groups.length,'unallocated',m.unallocatedGroups);
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>prisma.$disconnect());
